version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: "/dev/files-repo"
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: "/dev/salt-repo"
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: "/release/copy-bucket"
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: "/release/salt-yum-defs"
    schedule:
      interval: weekly
